# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-15 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170415_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='send_from',
        ),
        migrations.RemoveField(
            model_name='room',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='room',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='room',
            name='group',
        ),
        migrations.RemoveField(
            model_name='room',
            name='read',
        ),
        migrations.AddField(
            model_name='room',
            name='room_alias',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
