# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20161126_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='slug',
            new_name='label',
        ),
    ]
