# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20161126_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='context',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
