export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const VERIFY_FAILED = 'VERIFY_FAILED'

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_FAILED = 'REFRESH_FAILED'

export const LOGOUT = 'LOGOUT'

export const LOAD_FAILED = 'LOAD_FAILED'


export const LOAD_USER = 'LOAD_USER'
// export const LOAD_USER_FAILED = 'LOAD_USER_FAILED'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'


export const LOAD_CLASSROOMS = 'LOAD_CLASSROOMS'
// export const LOAD_CLASSROOM_FAILED = 'LOAD_CLASSROOM_FAILED'
export const ADD_CLASSROOM = 'ADD_CLASSROOM'
export const REMOVE_CLASSROOM = 'REMOVE_CLASSROOM'


export const LOAD_FRIENDS = 'LOAD_FRIENDS'
// export const LOAD_FRIEND_FAILED = 'LOAD_FRIEND_FAILED'
export const ADD_FRIEND = 'ADD_FRIEND'
export const REMOVE_FRIEND = 'REMOVE_FRIEND'

export const LOAD_TASKS = 'LOAD_TASKS'
// export const LOAD_TASK_FAILED = 'LOAD_TASK_FAILED'
export const ADD_TASK = 'ADD_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'

export const LOAD_CHATROOMS = 'LOAD_CHATROOMS'
// export const LOAD_CHATROOM_FAILED = 'LOAD_CHATROOM_FAILED'
export const ADD_CHATROOM = 'ADD_CHATROOM'
export const REMOVE_CHATROOM = 'REMOVE_CHATROOM'
