// -------COMMON ---------
export const LOG_ERROR = 'LOG_ERROR'

// ------- USER --------
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const VERIFY_FAILED = 'VERIFY_FAILED'

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_FAILED = 'REFRESH_FAILED'

export const LOGOUT = 'LOGOUT'

export const LOAD_AVATAR = 'LOAD_AVATAR'
export const UPDATE_AVATAR = 'UPDATE_AVATAR'
export const UPDATE_AVATAR_FAILED = 'UPDATE_AVATAR_FAILED'

export const LOAD_USER = 'LOAD_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

export const LOAD_CLASSROOMS = 'LOAD_CLASSROOMS'
export const ADD_CLASSROOM = 'ADD_CLASSROOM'
export const REMOVE_CLASSROOM = 'REMOVE_CLASSROOM'

export const LOAD_FRIENDS = 'LOAD_FRIENDS'
export const ADD_FRIEND = 'ADD_FRIEND'
export const REMOVE_FRIEND = 'REMOVE_FRIEND'

export const LOAD_TASKS = 'LOAD_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'

export const LOAD_CHATROOMS = 'LOAD_CHATROOMS'
export const ADD_CHATROOM = 'ADD_CHATROOM'
export const REMOVE_CHATROOM = 'REMOVE_CHATROOM'

// ------ Classroom -------
export const SEARCH_CLASSROOMS = 'SEARCH_CLASSROOMS'

export const GET_CLASSROOM = 'GET_CLASSROOM'

export const USER_IN_CLASSROOM = 'USER_IN_CLASSROOM'
export const USER_NOT_IN_CLASSROOM = 'USER_NOT_IN_CLASSROOM'

export const JOIN_CLASSROOM = 'JOIN_CLASSROOM'
export const JOIN_CLASSROOM_FAILED = 'JOIN_CLASSROOM_FAILED'
export const QUIT_CLASSROOM = 'QUIT_CLASSROOM'
